### ISSUE TITLE
Change payload type of SequencerSpecific messages

### ISSUE THREAD

**Issue by newlandsvalley** [newlandsvalley/elm-comidi#9]
from String to List Int

**Comment by rhofour** [comment]
Sounds good to me. I'd suggest:

type alias Byte = Int

Then using List Byte instead so the intention is more clear. That's what I've been doing in my generate code.

**Comment by newlandsvalley** [comment]
OK - good suggestion.  and use this for SysEx, SequencerSpecific and Unspecified?

**Comment by rhofour** [comment]
Yeah, I think we should use it anywhere where we're representing bytes with ints. If you look at my https://github.com/rhofour/elm-comidi/blob/generate/src/Midi/Types.elm you'll see I've added a bunch of other type aliases to make things more clear.

**Comment by newlandsvalley** [comment]
Fixed via c26e51b981a7193b2b329a1d70de398dbc1cd29b.
